### ISSUE TITLE
Imgur error curious

### ISSUE THREAD

**Issue by sipa40** [butterscotchstallion/limnoria-plugins#106]
Hi, firstly ty for all the work you guys do. This imgur titler worked great for a couple of days then all of a sudden i get some kind of error about credits, which in turn produces a http 429 error which is basically denied, but it only calls for 2 links every 1 hr. I have the client id set the secret set. 
 line 153, in make_request
    raise ImgurClientRateLimitError()
ImgurClientRateLimitError: Rate-limit exceeded!
ERROR 2017-04-18T22:24:18 Exception id: 0xb8e6f
so im very new to this how do i stop this error? as no way i have reached any kind of limits. ty

**Comment by butterscotchstallion** [comment]
I don't think I've ever encountered this error and I have much more traffic to imgur than that. Is your code modified?

This post has some information about how to check the requests being made on your account. I hope this helps!

https://stackoverflow.com/questions/29805865/imgur-api-lots-of-credits-left-but-imgurclientratelimiterror-rate-limit-excee

**Comment by sipa40** [comment]
no never modify a thing. I even did a whole new git clone last night same
error. maybe its in my imgur app something with the secret or id. not sure
im afk right now but i can see later and post the whole error. maybe more
details lie in it. ty for response.

**Comment by butterscotchstallion** [comment]
I'll try to reproduce. Thanks for the details

**Comment by sipa40** [comment]
well now i logged in and it works fine.. so strange. Do you think it was
there server side messing something up?? btw love the work man. Im very
noobish in python  ut trying to learn a great deal. just small doses lol.
Now i get a parser error saying none specified go to threading.py change
BeautifulSoup ([your markup)]
to this
BeautifulSoup ([your markup], "lxml"
so ill try that. But its getting the imgur titles now. so strange.

**Comment by butterscotchstallion** [comment]
Could you paste the exact error you are seeing?

**Comment by sipa40** [comment]
Hi, It was working fine for a while then all of a suddedn it started again. 
ERROR 2017-04-19T20:07:13 ERROR opening http://imgur.com/search?q=/*removed* message: HTTP Error 429: Unknown Error 
only error so far if i can reproduce the other in a minute ill show you that.

**Comment by butterscotchstallion** [comment]
429 is rate limit as shown in the documentation above.

**Comment by sipa40** [comment]
yeh ill have a look at that. because i sifted through the logs and found that same error just with loads more info.

ERROR 2017-04-18T22:24:18 supybot Uncaught exception in ['t'].
Traceback (most recent call last):
  File "/home/beast3/.local/lib/python2.7/site-packages/supybot/callbacks.py", line 1305, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/beast3/.local/lib/python2.7/site-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/home/beast3/.local/lib/python2.7/site-packages/supybot/callbacks.py", line 1282, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/home/beast3/.local/lib/python2.7/site-packages/supybot/commands.py", line 1082, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/beast3/nfo/plugins/SpiffyTitles/plugin.py", line 438, in t
    title = self.get_title_by_url(url, channel)
  File "/home/beast3/nfo/plugins/SpiffyTitles/plugin.py", line 401, in get_title_by_url
    title = handler(url, info, channel)
  File "/home/beast3/nfo/plugins/SpiffyTitles/plugin.py", line 1103, in handler_imgur
    self.initialize_imgur_client(channel)
  File "/home/beast3/nfo/plugins/SpiffyTitles/plugin.py", line 292, in initialize_imgur_client
    self.imgur_client = ImgurClient(imgur_client_id, imgur_client_secret)
  File "/home/beast3/.local/lib/python2.7/site-packages/imgurpython/client.py", line 85, in __init__
    self.credits = self.get_credits()
  File "/home/beast3/.local/lib/python2.7/site-packages/imgurpython/client.py", line 94, in get_credits
    return self.make_request('GET', 'credits', None, True)
  File "/home/beast3/.local/lib/python2.7/site-packages/imgurpython/client.py", line 153, in make_request
    raise ImgurClientRateLimitError()
ImgurClientRateLimitError: Rate-limit exceeded!
ERROR

**Comment by sipa40** [comment]
yeh that article says to add 

    def __init__(self, client_id, client_secret, access_token=None, refresh_token=None, mashape_key=None):

that somewhere.

**Comment by sipa40** [comment]
Ohh you know. what. when i clicked that link. it said also by ip.. so if its on vpn maybe others are too. lol. so its just because of that i guarantee it. TY for pointing me in proper direction. Its gotta be due to ip. only thing i can think of.

**Comment by butterscotchstallion** [comment]
That sounds about right. VPN IPs are often shared and I'd even wager that imgur has lower rate limits for VPNs. Glad you figured it out.

Please open a new issue if you have any further problems :)
