### ISSUE TITLE
SpiffyTitles: YouTube url problem

### ISSUE THREAD

**Issue by iyx** [butterscotchstallion/limnoria-plugins#107]
Hello, any idea why this particular url does not work for me?

``https://www.youtube.com/watch?v=TGqZYZ-CBes``

This is the error message:

``ERROR 2017-07-07 00:46:42 supybot SpiffyTitles: Youtube API HTTP 502: <!DOCTYPE html>``

Followed by some html code, ending with,

``<p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>Thatâ€™s all we know.</ins>``

**Comment by butterscotchstallion** [comment]
502 could mean the API is under load at the time. For what it's worth, this URL works for me.

**Comment by iyx** [comment]
Probably. Other urls worked fine so I wasn't sure, but this one works too now.
