### ISSUE TITLE
Please add support to shrink/tiny the url as well as return the title!

### ISSUE THREAD

**Issue by seitzbg** [butterscotchstallion/limnoria-plugins#69]
Please add support to shrink/tiny the url as well as return the title!

**Comment by butterscotchstallion** [comment]
You can do this using the ShrinkUrl plugin: https://github.com/ProgVal/Limnoria/tree/master/plugins/ShrinkUrl

**Comment by seitzbg** [comment]
how do they work together ?  In the past only one plugin could handle input.

Bryan Seitz

**Comment by butterscotchstallion** [comment]
- !load ShrinkUrl
- !config supybot.plugins.ShrinkUrl.shrinkSnarfer True 

This will result in the bot appending the shortened URL on the end of the message, or a new line if there is not enough space.

**Comment by seitzbg** [comment]
Thanks it worked!!

On Sat, Oct 31, 2015 at 10:09:13PM -0700, Butterscotch Stallion wrote:
>   • !load ShrinkUrl
>   • !config supybot.plugins.ShrinkUrl.shrinkSnarfer True
> 
> This will result in the bot appending the shortened URL on the end of the
> message, or a new line if there is not enough space.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
             
Bryan G. Seitz

**Comment by butterscotchstallion** [comment]
Great :)
