### ISSUE TITLE
SpiffyTitles: Make wikipedia handler work for all languages?

### ISSUE THREAD

**Issue by iyx** [butterscotchstallion/limnoria-plugins#77]
It uses same API I suppose, so only matter of setting right regex for it?

**Comment by butterscotchstallion** [comment]
Maybe Wikipedia has a language parameter you can use here https://github.com/butterscotchstallion/limnoria-plugins/blob/master/SpiffyTitles/config.py#L157

or you can try changing this option:

https://github.com/butterscotchstallion/limnoria-plugins/blob/master/SpiffyTitles/config.py#L37

Let me know what works and I can update the documentation
