### ISSUE TITLE
SpiffyTitles: Dailymotion handler

### ISSUE THREAD

**Issue by iyx** [butterscotchstallion/limnoria-plugins#86]
I have just noticed.

Dailymotion handler doesn't work with with short links (generated under Export option at dailymotion).

e.g.
Working: http://www.dailymotion.com/video/x2brczo_terminator-genisys-trailer_shortfilms
Not working: http://dai.ly/x2brczo

**Comment by butterscotchstallion** [comment]
This still needs some more work
