### ISSUE TITLE
SpiffyTitles: Twitter support

### ISSUE THREAD

**Issue by bw4518** [butterscotchstallion/limnoria-plugins#90]
Any way to support twitter, in similar fashion as reddit?

Like part of this plugin for parsing out twitter links and displaying info does https://github.com/reticulatingspline/Tweety

**Comment by butterscotchstallion** [comment]
It's possible, yes - but it might be tricky due to how complicated the Twitter API is. I think last I checked that library doesn't work with the current version of the Twitter API. The library would have to support the current version and implement rate limiting as well.
