### ISSUE TITLE
Adding Mimetypes

### ISSUE THREAD

**Issue by informationist** [butterscotchstallion/limnoria-plugins#93]
hi.

"unacceptable mime type image/jpeg for url https://blog.imgur.com/wp-content/uploads/2016/01/OeiRVAS.jpg"

i know there's command to add mime type but it fails. how do i add extra mime types exactly to support all file types?  (if no title available, it can give resolution, fine name or any available data about file)

**Comment by butterscotchstallion** [comment]
It's a configuration value, actually! Set the "mimeTypes" value - it's a comma separated value. Please reopen if this doesn't answer your question.

**Comment by informationist** [comment]
hi. i already tried witg/without comma before file this issue. i can't fine the right way. my purpose is to support all file types on links. like jpeg image on this example. let me know if this is wrong setting;

.config supybot.plugins.spiffytitles.mimetypes text/html,image/jpeg

debug log;   "unacceptable mime type image/jpeg for url https://blog.imgur.com/wp-content/uploads/2016/01/OeiRVAS.jpg"
