### ISSUE TITLE
SpiffyTitles: YouTube error with live stream

### ISSUE THREAD

**Issue by iyx** [butterscotchstallion/limnoria-plugins#95]
Recently I noticed error `supybot SpiffyTitles: error getting video id from https://www.youtube.com/c/powerfuljre/live` when this link was sent in the channel.

**Comment by butterscotchstallion** [comment]
Yeah. This is due to how SpiffyTitles parses the video ID from the URL. Typically the URL looks like youtube.com/?v=video_id_here. As you can see in your example, there is no video id.

**Comment by butterscotchstallion** [comment]
I don't know what the expected behavior is here. If there's something you think should happen here, please feel free to reopen the issue.
